version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: roarr
    versions:
    - 4.0.1
    - 4.1.3
  - dependency-name: eslint
    versions:
    - 7.19.0
